### ISSUE TITLE
Error in file "src\SavageEd.hla" at line 533 [errid:78367/hlaparse.bsn]:

### ISSUE THREAD

**Issue by tablecell** [Androthi/HIDE#6]
Error in file "src\SavageEd.hla" at line 533 [errid:78367/hlaparse.bsn]:
Expected ':', encountered '('
(Possible undefined ID 'NOTE').
Near: << ( >>

HLAPARSE assembly failed with 1 errors
Return :1
------------------------------------------------------------------------
Build done
Processes launched : 1
Errors Returned :1

source code from https://github.com/Androthi/SavageEd

**Comment by Androthi** [comment]
I think the macro library headers may have become out dated. I will take a look. In the mean time, you can comment out the NOTE macro.

**Comment by tablecell** [comment]
Can HIDE  support othter  language ( like php or golang )  syntax highlight  just add by   some syntax config ?

**Comment by Androthi** [comment]
HIDE can support up to 16 different highlight color word sets. Each word
set is a space separate .ini document which you can edit manually (they are
located in the data folder) or using the Colors & Keywords dialog. The
group names are hard coded, but the actual keywords they contain can be
anything you want. You can also change the number/string colors, but
comments are hard coded to C style.

The Projects and Build system however are hard coded for only HLA files. If
you want to build other language types, it will require editing the HIDE
source.  Keep in mind that HIDE is a pretty old IDE (I wrote it I think
around 2007-2008) that was designed for use with HLA. There are better
modern options to use with golang or php (like VS Code ).

**Comment by Androthi** [comment]
new version in release section.

**Comment by tablecell** [comment]
```
Build: SavageEd
Link :SavageEd
------------------------------------------------------------------------
Build done
Processes launched : 1
Errors Returned :0
```
HIDE v1.6.52 compile SavageEd-master  ok   
this  SavageEd compiled  version  can select customized background color which other executable version can not .

**Comment by Androthi** [comment]
are you using an old .ini file with the other compiled version of SavageEd? sometimes .ini files become outdated when new features are added, this may result in some settings not setting properly.

**Comment by tablecell** [comment]
version 1.4.6
[v1.4.6.zip](https://github.com/Androthi/HIDE/files/7144286/v1.4.6.zip)

**Comment by tablecell** [comment]
I add  golang keywords to   data\user01.ini 
and set color  from Option/General/Themes  
when open file test.go but nothing happened 
![theme](https://user-images.githubusercontent.com/6591466/132869706-9541bfb6-61c6-4630-b307-82e0c0ba26eb.jpg)

How setup data\user01.ini bind golang file syntax highlight ?
Is there any guide   add  other language  syntax highlight  config (like golang)    for data\xx.ini 
like  
- step 1 
- step 2
- step 3
...

**Comment by Androthi** [comment]
There is no guide for it. These are the .ini files you can change. They are
all located in the data folder. If the user ones don't exist, you can
create them.

"x86 Registers",
"x86 Instructions",
"x86 Extended",
"Resource",
"HLA Keywords",
"HLA Types",
"HLA Namespace",
"HLA Stdlib",
"HLA CTL",
"API Constants",
"API Functions",
"User 01",
"User 02",
"User 03",
"User 04",
"User 05"

Each one of these files can correspond to a different color which you can
set in the Colors & Keywords dialog.
You can either add/remove keywords from that dialog, which is a slow
process only intended to add one or two at a time.
The other option is to edit the files yourself. Each file is a single line
with all the keywords separated by a single space.

Go has 25 keywords, so right away, you can edit the data\HLA Keywords.ini
file and put this line in it:

break default func interface select case defer go map struct chan else goto
package switch const fallthrough if range type continue for import return
var

You can just save all the other files as empty files if you don't want the
keywords they contain. A good place to put Golang standard library
functions is in data\HLA Stdlib.ini
You might also want to edit the data\HLA Types.ini and put Golang types in
there instead.

I don't know why you would want to use HIDE with Golang. Most of the
features will be locked out, the autocomplete was always limited and
doesn't compare to modern IDEs. You could potentially add a kmake script to
the project to compile it, but that will require learning how to use kmake
in the Help-> HIDE Tools documents. Or modifying the HIDE source itself.
Also, a lot of this stuff I haven't used in years, so I don't know how well
they work.

**Comment by tablecell** [comment]
put  Golang keywords  to   data\HLA Keywords.ini
rename test.go  to  test.hla   
open test.hla 
It works.
![test-hla](https://user-images.githubusercontent.com/6591466/132879751-7ae088b1-8670-456f-aec3-84ac7dc812d0.jpg)


But when  open  test.go   it render plain text have no syntax highlight 
Is there any solution   to bind  data\user01.ini to  *.go  except recompiling  HIDE  
for examle 
- data\HLA Keywords.ini   [ABSTRACT ALIGN ANYEXCEPTION BEGIN ...]  =>  *.hla 
- data\user01.ini               [package  import  func     go    defer   interface  chan...]   => *.go 
...

**Comment by Androthi** [comment]
hm. I had forgotten that HIDE was hard coded to have "Job" modes and highlighting only in project mode using the Program Job.

quick tutorial:
1. Project -> New Project
2. type "TestGo" in the project name field. leave everything else the way it is, OK.
3. in the HIDE Manager the pops up, click the Jobs tab
4. click New at the top. Keep the Job Type as Program and enter a Job name, "TestGo"
5. Now click on TestGo in the list
6. Next to the File list below, click New button
7. In the File Type field, it should be HLA Program, HLA Unit or HLA Header, type a file name you want, make sure to enter .go extension.
8. eg: MyGo.go
9. Click set

Now you should be able to use the .go files with highlighting. You can add more files to the project by repeating steps 5-9 in the Project -> Job Manager

I know it's a bit contrived, but like I said, this project is over 13 years old and I wasn't too experienced back then.
The way HIDE is set up, a "Project" is a list of "Jobs" where each "Job" is supposed to do a different thing.

Compare it to Visual Studio, a "Project" is the same as a VS "Solution" and a "Job" is the same as a VS "Project"

**Comment by tablecell** [comment]
It's works! thanks for the tutorial.
![job](https://user-images.githubusercontent.com/6591466/132930889-5d56f824-0203-4214-ad68-a0e920a70ddf.jpg)

and thank you for all your support.
wrote HIDE is really  a good "Job"
